### ISSUE TITLE
Temp and RH coming up as 0.0 in Score Summary

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#359]
@adolski @suhailsheth @jhain 

Suhail noticed that temp and RH are both showing up as 0.0 in the Score Summary formula box. This happens with both old and new resources. Here is the example: 
![temp_rh in summary](https://cloud.githubusercontent.com/assets/19311155/20158491/22356faa-a6a0-11e6-93e1-f401167c2b30.JPG)

So, it appears that even though they should each be contributing 0.025 to the overall Resource score, the temp and RH are contributing nothing. Jennifer is going to look a little deeper into the math in the scoring matrix, but I want to at least get this issue on the radar since there isn't much time left on this project. **Any chance this could just be a bug that is leaving out the temp and RH scoring in the summary scores??**

Also FYI: The temp and RH questions are also weighted as 0.0 in the location QUESTIONS  (see image below) - but I figured that was because the temp and RH scores are actually pulled from the Format Scores sheet of the question dependencies spreadsheet, not the Location sheet of the spreadsheet (since the temp and RH vary according to format, even though we ask about them in the "Location Assessment." 
![temp_rh in question](https://cloud.githubusercontent.com/assets/19311155/20158247/dac04fa6-a69e-11e6-9813-419580eb0696.PNG)

**Comment by adolski** [comment]
I found the bug that was causing the zero temp/RH scores. The fix has been deployed to psap-stage.

Re: your last paragraph, that is correct, AFAIK.

**Comment by jhain** [comment]
Thanks!!!!

**Comment by adolski** [comment]
In the "Format Scores" tab of the assessment questions spreadsheet, "Archaeological Glass" has an RH score of 0 for min RH 0 and max RH 29.

Typo?

**Comment by spelczar** [comment]
Nope - that RH 0 for archaeological glass is actually correct. My bad. Closing this issue.

**Comment by spelczar** [comment]
@adolski @suhailsheth

The 0.0 temp scoring problem is back in a few places, which is weird, because the RH numbers seem to be working OK.
Example:
Location with 0-32F and 30-40%RH, archaeological nickel **should** come up with temp score of 0.33 but
Scores appear in score summary as: 
Its temperature score is 0.0.
Its relative humidity score is 100.0. (RH is correct)

Same thing is happening for stone materials - which are coming up with 0.0 temp score for 73-120F temp range, even though the spreadsheet has them scored as 0.33 for that range. The 0.0 score is also showing up on 0-33F temp score for Stone, even though 0-33F is scored as **0.33**. 

We have double checked the format scores sheet in the question dependencies spreadsheet. Could this be a bug/glitch?

**Comment by spelczar** [comment]
FYI: seems to be happening only with scores that should be 0.33.

**Comment by adolski** [comment]
@spelczar Can you post a psap-stage URL where this is happening?

**Comment by adolski** [comment]
@spelczar Nevermind, I see it. Fix attempt will be on psap-stage shortly.

**Comment by spelczar** [comment]
Sure try this: https://psap-stage.library.illinois.edu/resources/20
here's a screen capture in case that link doesn't work. The temp score is coming up as 0.0 and RH score as 75
![chert0 0temp](https://cloud.githubusercontent.com/assets/19311155/20495044/2204e7ce-afe5-11e6-9d27-2fd8e7ec1ffc.JPG)

here's a screen capture of the Location Assessment where you can see that the selected temp for that Location that the above chert object is in is 0-32F, with an RH of 30-40%. 
![chertgoodenviro zero-32](https://cloud.githubusercontent.com/assets/19311155/20495131/70b22922-afe5-11e6-8072-904ffa5390a5.JPG)

According to the format scores sheet in the question dependencies spreadsheet, the score for 0-32F temp should be 0.33, not 0.0 (the 75 score for the 30-40% RH is correct)
![formatscorestemp](https://cloud.githubusercontent.com/assets/19311155/20495230/cbc2d884-afe5-11e6-9b44-276f523cefc7.JPG)

Does that help? From what we can tell, the issue is only happening with 0.33 scores (changing 0.33 scores to 0.0 scores instead). So, it happens a lot with stone since 0.33 is the score at the top and bottom range of the stone temps; but I've also seen it happen with the 0.33 scores at the bottom range of the metal temps.

**Comment by spelczar** [comment]
oops, I was drafting my response when you send your "never mind" message. Ah well.

**Comment by adolski** [comment]
Thanks for the explanation, @spelczar. I believe this was caused by a bug. The fix has been deployed to psap-stage.

**Comment by spelczar** [comment]
thanks.
